INSERT INTO skills (skill_name) VALUES
    ('Communication'),
    ('English'),
    ('Khmer'),
    ('Microsoft Office'),
    ('Excel'),
    ('Customer Service'),
    ('Sales'),
    ('Digital Marketing'),
    ('Accounting'),
    ('Finance'),
    ('QuickBooks'),
    ('CRM'),
    ('Leadership'),
    ('Problem Solving'),
    ('Project Management'),
    ('Procurement'),
    ('Logistics'),
    ('Teaching'),
    ('Graphic Design'),
    ('Adobe Photoshop'),
    ('Adobe Illustrator'),
    ('Reporting'),
    ('Data Collection'),
    ('Python'),
    ('SQL'),
    ('Power BI'),
    ('Tableau'),
    ('Statistics'),
    ('Data Visualization'),
    ('Data Cleaning'),
    ('Machine Learning'),
    ('Git'),
    ('JavaScript'),
    ('API Development'),
    ('Network Support')
ON CONFLICT (skill_name) DO NOTHING;
